# docker-compose.yml
version: '3.8'

services:
  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_DB: comments_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    restart: always
    ports:
      - "8088:8088"
    environment:
      DATABASE_URL: postgres://user:password@db:5432/comments_db
    depends_on:
      - db
    volumes:
      - ./backend:/app
      - /app/node_modules # Anonymous volume to prevent host node_modules from overriding container's

  frontend:
    build: ./frontend
    restart: always
    ports:
      - "3001:3000" # Map host port 3001 to container port 3000
    environment:
      NEXT_PUBLIC_API_BASE: http://localhost:8088/api # This will be the backend URL from the frontend's perspective
    depends_on:
      - backend
    volumes:
      - /app/node_modules # Anonymous volume

volumes:
  db_data: